# Generated by Django 5.1.4 on 2025-01-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="article",
            name="excerpt",
            field=models.TextField(blank=True, null=True, verbose_name="Excerpt"),
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="Content"),
        ),
    ]
