# Generated by Django 5.1.4 on 2025-01-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_category_options_article_excerpt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="article",
            name="excerpt",
            field=models.TextField(
                blank=True, default="Excerpt not available", verbose_name="Excerpt"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="article",
            name="meta_description",
            field=models.TextField(
                blank=True,
                default="Generated automatically. Please review.",
                max_length=160,
                verbose_name="Meta Description",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="meta_description",
            field=models.TextField(
                blank=True,
                default="Generated automatically. Please review.",
                max_length=160,
                verbose_name="Meta Description",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tag",
            name="meta_description",
            field=models.TextField(
                blank=True,
                default="Generated automatically. Please review.",
                max_length=160,
                verbose_name="Meta Description",
            ),
            preserve_default=False,
        ),
    ]
