# Generated by Django 5.1.4 on 2025-01-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_article_content_alter_article_excerpt_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Auction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auction_id", models.CharField(max_length=20, unique=True)),
                ("code", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=50)),
                ("title", models.TextField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("detail_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["auction_id"], name="blog_auctio_auction_1794d7_idx"
                    ),
                    models.Index(
                        fields=["start_date"], name="blog_auctio_start_d_f8293c_idx"
                    ),
                    models.Index(
                        fields=["status"], name="blog_auctio_status_e34758_idx"
                    ),
                ],
            },
        ),
    ]
