# Generated by Django 5.1.4 on 2024-12-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_remove_tag_meta_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="meta_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Meta Description"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="meta_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Meta Description"
            ),
        ),
    ]
